In [1]:
#STEP 1: LOAD THE IRIS DATA SET
import pandas as pd

data = pd.read_csv(r"C:\Users\Rohan\Downloads\Iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
#STEP 2: STANDARDIZE THE DATA

from sklearn.preprocessing import StandardScaler
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

In [5]:
# Separating features and target
x = data.loc[:, features].values
y = data.loc[:,['Species']].values

In [7]:
# Standardizing the features(the result is stored in x)
x = StandardScaler().fit_transform(x)

In [9]:
# Convert to DataFrame for better visualization
df1 = pd.DataFrame(x)
df1

            0         1         2         3
0   -0.900681  1.032057 -1.341272 -1.312977
1   -1.143017 -0.124958 -1.341272 -1.312977
2   -1.385353  0.337848 -1.398138 -1.312977
3   -1.506521  0.106445 -1.284407 -1.312977
4   -1.021849  1.263460 -1.341272 -1.312977
..        ...       ...       ...       ...
145  1.038005 -0.124958  0.819624  1.447956
146  0.553333 -1.281972  0.705893  0.922064
147  0.795669 -0.124958  0.819624  1.053537
148  0.432165  0.800654  0.933356  1.447956
149  0.068662 -0.124958  0.762759  0.790591

[150 rows x 4 columns]

In [11]:
# Verify mean and standard deviation
print("Mean of each feature after standardization:")
print(df1.mean().round(6))  # Should be approximately 0

#print("\nStandard deviation of each feature after standardization:")
print(df1.std(ddof=0).round(6))  # ddof=0 ensures that the formula matches what StandardScaler

Mean of each feature after standardization:
0   -0.0
1   -0.0
2    0.0
3   -0.0
dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

In [12]:
STEP 3: FIT PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=2)    #Giving PCA with No. of components
pca

SyntaxError: invalid syntax (4030712296.py, line 1)

In [ ]:
#Performing PCA Transformation
principalComponents = pca.fit_transform(x)
principalComponents

In [ ]:
principalDf = pd.DataFrame(data = principalComponents, columns = ['PC 1', 'PC 2'])
principalDf        #Contains PC

In [ ]:
finalDf = pd.concat([principalDf, data[['Species']]], axis = 1)    
finalDf

In [ ]:
pca.explained_variance_ratio_

In [ ]:
import matplotlib.pyplot as plt
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 2', fontsize = 15)
ax.set_title('2 component PCA', fontsize = 20)

targets = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
colors = ['r', 'g', 'b']
for target, color in zip(targets,colors):
    indicesToKeep = finalDf['Species'] == target
    ax.scatter(finalDf.loc[indicesToKeep, 'PC 1']
               , finalDf.loc[indicesToKeep, 'PC 2']
               , c = color
               , s = 50)
ax.legend(targets)
ax.grid()